<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>DocUpload demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">

    <style>
    body {
        background-color: #F7E7DC;
    }

    .custom-file-button input[type=file] {
        margin-left: -2px !important;
    }

    .custom-file-button input[type=file]::-webkit-file-upload-button {
        display: none;
    }

    .custom-file-button input[type=file]::file-selector-button {
        display: none;
    }

    .custom-file-button:hover label {
        background-color: #dde0e3;
        cursor: pointer;
    }
    </style>
</head>

<body>
    <main>
        <h1 class="text-center m-4">Clone Transfer Dana</h1>
        <div class="container py-3">
            <?= $this->resftr; ?>
            <form method="POST" action="" enctype='multipart/form-data'>
                <section class="d-flex align-items-center justify-content-center">
                    <div class="card" style="width: 25rem">
                        <div class="card-header">
                            <select class="form-select" aria-label="Default select example" name='transferDana'>
                                <option selected>INDOMARET / MT940</option>
                                <option value="INDOMARET">Indomaret</option>
                            </select>
                            <option value="MANDIRI_MT940">Mandiri MT940</option>
                        </div>
                        <div class="input-group custom-file-button my-3 card-header">
                            <label class="input-group-text" for="inputGroupFile">Upload file disini</label>
                            <input type="file" class="form-control" id="inputGroupFile" name='ftrFile'>
                        </div>
                        <div class="card-body form-actions mx-auto">
                            <button type="submit" class="btn btn-large btn-info" name="proses" value="importDoc">
                                Import Document
                            </button>
                            <button type="submit" class="btn btn-large btn-danger" name="proses" value="generateDoc">
                                Generate Document
                            </button>
                            <br>
                            <button class="btn btn-large btn-outline-primary mt-4" style="padding: 6px 34px 6px 34px;">
                                Rekonsiliasi
                            </button>
                            <button class="btn btn-large btn-outline-warning mt-4" style="padding: 6px 58px 6px 58px;">
                                Pantau
                            </button>
                        </div>
                    </div>
                </section>
            </form>

            <section>
                <?php 
    if (is_array($this->dataIndomaret)) {
        echo "<div class='widget'>";
        echo "<div class='widget-title'>";
        echo "<h4><i class='icon-reorder'></i> TABLE PANTAU TRANSAKSI MT940</h4>";
        echo "</div>";
        echo "<div class='widget-body'>";
        echo "<form method='POST' action=''>";
        echo "<input type='hidden' name='proses' value='delete'>";
        echo "<table class='table table-striped table-bordered' id='tablercn'>";
        echo "<thead>";
        echo "<tr>";
        echo "<th>Select All<input type='checkbox' id='selectAll'></th>";
        echo "<th class='hidden-phone'>NO</th>";
        echo "<th class='hidden-phone'>TANGGAL TRANSAKSI</th>";
        echo "<th class='hidden-phone'>TERMINAL ID</th>";
        echo "<th class='hidden-phone'>NAMA PP</th>";
        echo "<th class='hidden-phone'>ID TRX</th>";
        echo "<th class='hidden-phone'>REFF ID</th>";
        echo "<th class='hidden-phone'>TRACE NUMBER</th>";
        echo "<th class='hidden-phone'>TRAN AMOUNT</th>";
        echo "<th class='hidden-phone'>ADMIN BANK</th>";
        echo "<th class='hidden-phone'>TRX</th>";
        echo "<th class='hidden-phone'>TRANSACTION NUMBER</th>";
        echo "</tr>";
        echo "</thead>";
        echo "<tbody>";
        $no = 1;
        foreach ($this->dataIndomaret as $data) {
            echo "<tr>";
            echo "<td><input type='checkbox' name='delete[]' value='" . $data['id'] . "' class='delete-checkbox'></td>";
            echo "<td>" . $no++ . "</td>";
            echo "<td>" . $data['vTGL_TRANSAKSI'] . "</td>";
            echo "<td>" . $data['vTERMINAL_ID'] . "</td>";
            echo "<td>" . $data['vNAMA_PP'] . "</td>";
            echo "<td>" . $data['vID_TRX'] . "</td>";
            echo "<td>" . $data['vREFF_ID'] . "</td>";
            echo "<td>" . $data['vTRACE_NUMBER'] . "</td>";
            echo "<td>" . $data['vTRAN_AMOUNT'] . "</td>";
            echo "<td>" . $data['vADMIN_BANK'] . "</td>";
            echo "<td>" . $data['vTRX'] . "</td>";
            echo "<td>" . $data['vTRANSACTION_NUMBER'] . "</td>";
            echo "</tr>";
        }
        echo "</tbody>";
        echo "</table>";
        echo "<button type='submit' id='deleteButton'>Delete Selected</button>";
        echo "</form>";
        echo "</div>";
        echo "</div>";
    }
    ?>
            </section>

        </div>
    </main>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous">
    </script>
    <script>
    document.addEventListener('DOMContentLoaded', function() {
        document.getElementById('selectAll').addEventListener('change', function() {
            var checkboxes = document.querySelectorAll('.delete-checkbox');
            for (var checkbox of checkboxes) {
                checkbox.checked = this.checked;
            }
        });
    });
    </script>
</body>

</html>