<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>DocUpload demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">

    <style>
    body {
        background-color: #F7E7DC;
    }

    .custom-file-button input[type=file] {
        margin-left: -2px !important;
    }

    .custom-file-button input[type=file]::-webkit-file-upload-button {
        display: none;
    }

    .custom-file-button input[type=file]::file-selector-button {
        display: none;
    }

    .custom-file-button:hover label {
        background-color: #dde0e3;
        cursor: pointer;
    }
    </style>
</head>

<body>
    <main>
        <h1 class="text-center m-4">Clone Transfer Dana</h1>
        <div class="container py-3">
            <?= $this->resftr; ?>
            <form method="POST" action="" enctype='multipart/form-data'>
                <section class="d-flex align-items-center justify-content-center">
                    <div class="card" style="width: 25rem">
                        <div class="card-header">
                            <select class="form-select" aria-label="Default select example" name='transferDana'>
                                <option selected>INDOMARET / MT940</option>
                                <option value="INDOMARET">Indomaret</option>
                            </select>
                            <option value="MANDIRI_MT940">Mandiri MT940</option>
                        </div>
                        <div class="input-group custom-file-button my-3 card-header">
                            <label class="input-group-text" for="inputGroupFile">Upload file disini</label>
                            <input type="file" class="form-control" id="inputGroupFile" name='ftrFile'>
                        </div>
                        <div class="card-body form-actions mx-auto">
                            <button type="submit" class="btn btn-large btn-info" name="proses" value="importDoc">
                                Import Document
                            </button>
                            <button type="submit" class="btn btn-large btn-danger" name="proses" value="generateDoc">
                                Generate Document
                            </button>
                            <br>
                            <button class="btn btn-large btn-outline-primary mt-4" style="padding: 6px 34px 6px 34px;">
                                Rekonsiliasi
                            </button>
                            <button class="btn btn-large btn-outline-warning mt-4" style="padding: 6px 58px 6px 58px;">
                                Pantau
                            </button>
                        </div>
                    </div>
                </section>
            </form>
        </div>
    </main>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous">
    </script>
</body>

</html>